### ISSUE TITLE
Memory Leaks - Join to #hello channel and Quit

### ISSUE THREAD

**Issue by gerry-mandering** [geneeol/ft_irc-cpp#73]
```
>====== numEvents: 1 ======<

18:38:16 [TRACE] event ident: 5
18:38:16 [TRACE]  READ event
18:38:16 [TRACE] nread: 15
18:38:16 [TRACE] [ 5 ] sent data: QUIT :leaving

18:38:16 [TRACE] crlf_pos: 13
18:38:16 [DEBUG] Extracted request: QUIT :leaving

18:38:16 [DEBUG] Reamin buffer len: 0,
18:38:16 [DEBUG] Try parse: QUIT :leaving

18:38:16 [TRACE]  command: QUIT
18:38:16 [TRACE]  command: QUIT
18:38:16 [TRACE]  message: :leaving
18:38:16 [TRACE] ClientRepository FindBySocket() - Found
18:38:16 [TRACE] PrivmsgRequest constructor called | QuitRequest = { Reason: :leaving }
18:38:16 [DEBUG] Parsing success
18:38:16 [TRACE] QuitRequest Validated
18:38:16 [DEBUG] Add response to handler's wrbuf: :minseok2!root@root Quit :Quit: :leaving

18:38:16 [DEBUG] [ 5 ] register WRITE_EVENT
18:38:16 [TRACE] QuitRequest Executing - BroadcastMessage
18:38:16 [TRACE] ClientRepository RemoveClient()
18:38:16 [INFO ] [ 5 ]: disconnect
18:38:16 [TRACE] ClientRepository FindBySocket() - NotFound
18:38:16 [INFO ]  Client not found for socket 5
18:38:16 [TRACE] QuitRequest Executed
18:38:16 [TRACE] event loop
18:38:16 [TRACE]
>====== numEvents: 1 ======<

18:38:16 [TRACE] event ident: 5
18:38:16 [TRACE]  EOF event
18:38:16 [INFO ] [ 5 ]: disconnect
18:38:16 [TRACE] ClientRepository FindBySocket() - NotFound
AddressSanitizer:DEADLYSIGNAL
=================================================================
==30248==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000109c73f6d bp 0x7ffee5ff6c10 sp 0x7ffee5ff69e0 T0)
==30248==The signal is caused by a READ memory access.
==30248==Hint: address points to the zero page.
    #0 0x109c73f6d in Reactor::unregisterHandler(EventHandler*) Reactor.cpp:44
    #1 0x109c84983 in disconnect(int) disconnect.cpp:22
    #2 0x109c7f7df in StreamHandler::handleDisconnect() StreamHandler.cpp:114
    #3 0x109c63187 in KqueueDemultiplexer::waitEvents(std::__1::map<int, EventHandler*, std::__1::less<int>, std::__1::allocator<std::__1::pair<int const, EventHandler*> > >&) KqueueDemultiplexer.cpp:95
    #4 0x109c7494a in Reactor::handleEvents() Reactor.cpp:69
    #5 0x109d16fc5 in main main.cpp:102
    #6 0x7fff7155fcc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

==30248==Register values:
rax = 0x0000000000000000  rbx = 0x00007ffee5ff6aa0  rcx = 0x00007ffee5ff6a00  rdx = 0x00007ffee5ff6a10
rdi = 0x00007ffee5ff6a50  rsi = 0x00007ffee5ff6a30  rbp = 0x00007ffee5ff6c10  rsp = 0x00007ffee5ff69e0
 r8 = 0x00007ffee5ff6a70   r9 = 0x00001fffdcbfed3c  r10 = 0x0000100000000000  r11 = 0x0000604000000350
r12 = 0x0000100000000000  r13 = 0x0000000000000000  r14 = 0x0000000000000000  r15 = 0x0000000000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV Reactor.cpp:44 in Reactor::unregisterHandler(EventHandler*)
==30248==ABORTING
[1]    30248 abort      ./ircserver 6667 1234
```

**Comment by gerry-mandering** [comment]
Issue Closed
